
  project_name: "Curculionidae of the World Online"
  project_citation: "Curculionidae of the World Online. TaxonPages"
  project_url: https://curculionidae.github.io/taxa
  project_authors: "Yunakov, N., Girón Duque, J.C., Brown, S., Jilg, J., Meregalli, M., del Río, M.G., Rincón, J., Cortés-Hernández, K., Cabras, A. (2025)."
