  project_name: "TaxonPages: Curculionidae of the World"
  project_citation: "Curculionidae of the World. TaxonPages"
  project_url: https://curculionidae.github.io/taxa
  project_authors: "Yunakov, N., Girón Duque, J.C., Brown, S., del Río, M.G., Rincón, J., Cortés-Hernández, K., Cabras, A.  (2024)."
